Jinja2's escape module is required, this fixes the error "ImportError: cannot import name 'escape' from 'jinja2'"
Ref: https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2